### PR TITLE
Added LICENSE

### PR DESCRIPTION
**Pull request by gaycomputers**
GNU GPL v3 as listed here: https://launchpad.net/click

### CODE REVIEW

**Review by abhishek-mudgal — APPROVED** [review]

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
LICENSE is spelled without the first S. Please rename the file, then I'll merge this.

**Comment by gaycomputers** [comment]
Whoops

**Comment by UniversalSuperBox** [comment]
The name of the file in the commit is also incorrect

**Comment by gaycomputers** [comment]
Definitely fixed now I believe

**Comment by UniversalSuperBox** [comment]
Very nice, thank you!

**Pull request merged**
